name: freeplay
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  get_it: ^7.2.0
  injectable: ^1.5.3
  cupertino_icons: ^1.0.2
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  freezed: ^2.0.3+1
  copy_with_extension_gen: ^4.0.2
  gradient_widgets: ^0.6.0
  flutter_screenutil: ^5.3.0
  charts_flutter: ^0.12.0
  flutter_onboarding_screen: ^2.0.2
  shared_preferences: ^2.0.13
  provider: ^6.0.2
  page_transition: ^2.0.5
  flutter_svg: ^1.1.5
  auto_route: ^5.0.1
  flutter_dotenv: ^5.0.2
  dio: ^4.0.6
  global_snack_bar: ^0.0.12
  dio_logger: ^4.0.8+8
  encrypt: ^5.0.3
  flutter_native_splash: 2.2.10+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  package_info_plus: ^1.4.3+1
  # timezone: ^0.9.0
  sliding_up_panel: ^2.0.0+1
  currency_text_input_formatter: ^2.1.7
#  flutter_native_timezone: ^2.0.0
  dotted_border: ^2.0.0+2
  cached_network_image: ^3.2.2
  bordered_text: ^2.0.0
  intl: ^0.17.0
  url_launcher: ^6.2.6
  firebase_core: ^2.32.0
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^17.1.2
  device_info_plus: any
  flutter_timezone: ^1.0.8
  popover: ^0.2.8+2
  pull_to_refresh: ^2.0.0
  http: ^0.13.5
  simple_gradient_text: 1.3.0
  badges: ^3.1.2
  appsflyer_sdk: ^6.14.3
  flutter_date_picker_timeline: ^0.3.3
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.4
  auto_route_generator: ^5.0.2
  device_info_plus: ^4.1.2
  flutter_launcher_icons: ^0.10.0

dependency_overrides:
  package_info_plus: ^4.0.1
  wakelock_windows: any
  win32: any

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo/app.png"

flutter_native_splash:
  color: "#212340"
  image: assets/images/app_splash/freeplay_logo.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    # image: assets/images/app_splash/android12_splash.png

    # Splash screen background color.
    color: "#212340"

    # App icon background color.
    # icon_background_color: "#212340"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"

  web: false

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/icons/home/
    - assets/images/auth/
    - assets/images/app_logo/
    - assets/images/app_splash/
    - assets/images/dialog_images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
        - asset: assets/fonts/Raleway-Light.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
          
  

